language: ruby
# cache: bundler
sudo: false
rvm:
  - 2.3.0
env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
before_script:
  - jdk_switcher use oraclejdk8
  - gdalinfo --version
services:
  - redis-server
addons:
  apt:
    packages:
    - gdal-bin
